safe_notification_service/safe/tasks.py, safe_notification_service/version.py
=>  Set version 1.1.2

safe_notification_service/safe/management/commands/check_invalid_tokens.py, safe_notification_service/version.py
=>  Set version 1.1.3

requirements.txt, safe_notification_service/safe/serializers.py, safe_notification_service/version.py
=> Set version 1.1.4

safe_notification_service/safe/serializers.py, safe_notification_service/safe/tests/factories.py, safe_notification_service/safe/tests/test_serializers.py, safe_notification_service/safe/tests/test_views.py, safe_notification_service/safe/views.py, safe_notification_service/version.py
- Fix device pair delete endpoint
=> Set version v1.1.5

safe_notification_service/firebase/client.py
=>  fixes mutable content

requirements.txt, safe_notification_service/version.py
- Fix mutable content for iOs @DmitryBespalov
=> Set version v1.2.1

.gitignore, safe_notification_service/safe/models.py, safe_notification_service/safe/serializers.py, safe_notification_service/safe/tests/test_serializers.py, safe_notification_service/safe/tests/test_views_v2.py
- Remove check if `version_name` complies to https://www.python.org/dev/peps/pep-0440/
=> Allow arbitrary version names

requirements-test.txt, requirements.txt, safe_notification_service/safe/models.py, safe_notification_service/safe/serializers.py, safe_notification_service/safe/services/auth_service.py, safe_notification_service/safe/tests/test_serializers.py, safe_notification_service/safe/tests/test_views_v2.py, safe_notification_service/version.py
- Force DeviceType to be always lowercase
=>  Set version 1.3.2

config/settings/base.py, safe_notification_service/safe/services/auth_service.py, safe_notification_service/safe/tests/test_views_v2.py, safe_notification_service/safe/views.py, safe_notification_service/version.py
=>  Set version v1.3.3

README.md, requirements-test.txt, requirements.txt, safe_notification_service/safe/services/auth_service.py, safe_notification_service/safe/views.py, safe_notification_service/version.py
- Log when owner registers a device
- Update libraries
=> Set v1.3.5

safe_notification_service/safe/admin.py, safe_notification_service/version.py
=> Set version 1.4.3

.gitignore, requirements-test.txt, requirements.txt, safe_notification_service/version.py
=> Set version v1.4.7

safe_notification_service/version.py
Changelog: https://github.com/gnosis/safe-notification-service/compare/v1.5.5...bump-version
=> Bump version to 1.5.6

.github/workflows/python.yml, safe_notification_service/version.py
- The pipeline was not being triggered for release events so the deployment step would never run
=> Trigger pipeline for release events

safe_notification_service/version.py
Changelog: https://github.com/gnosis/safe-notification-service/compare/v1.5.8...bump-service-version-1.5.9
=> Bump service version to 1.5.9

safe_notification_service/version.py
Changelog: https://github.com/gnosis/safe-notification-service/compare/v1.5.9...master
=> Bump service version from 1.5.9 to 1.5.10

.github/workflows/python.yml, scripts/autodeploy.sh
- Removed Dockerhub autodeploy weebhooks
- Added new step for the autodeploy request after the image is built
- Added auth to autodeploy service, now is more secure the deployment of new versions.
- Added nginx auth script
=> Autodeploy auth

safe_notification_service/version.py
Release: https://github.com/5afe/safe-notification-service/releases/tag/v1.5.12
=> Backmerge release 1.5.12

.github/workflows/python.yml
Closes #
@gnosis/safe-services
=> Remove autodeploy

safe_notification_service/version.py
Release: https://github.com/5afe/safe-notification-service/releases/tag/v1.5.14
=> Backmerge release 1.5.14
